<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>The Evolution of Visual Entertainment</title>
	<link rel="stylesheet" type="text/css" href="css/styles.css">
	<link href="https://fonts.googleapis.com/css?family=Lato|Roboto:300,400" rel="stylesheet">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>

<body>
<main>
	<header>
		<h1>Spare-time activities</h1>
	</header>
